version: '3.1'
services:
  django:
    container_name: django_tutorial
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/app/
    ports:
      - 8000:8000
    environment:
      TZ: Asia/Tokyo
    tty: true
