name: Run pytest

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v1
    - name: Set up Python 3.8.1
      uses: actions/setup-python@v2
      with:
        python-version: 3.8.1
    - name: Install pipenv and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv --upgrade-strategy=only-if-needed
        pipenv install --dev
    - name: Save cache
      uses: actions/cache@v1
      with:
        path: |
          ~/.venv
          ~/.cache/pipenv
          /usr/local/bin
          /usr/local/lib/python3.8/site-packages
        key: ${{ runner.os }}-${{ hashFiles('**/Pipfile.lock') }}
    - name: Run test
      run: |
        pipenv run test